---
- name: Install NFS server dependencies
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
      - autofs
    state: latest

- name: Create NFS mountpoints - clients
  file:
    path: "{{ item.mountpoint }}"
    state: directory
  loop: "{{ autofs_mounts }}"
  when: autofs_mounts is defined
  ignore_errors: true

- name: Add exports to /etc/exports
  blockinfile:
    path: /etc/exports
    block: |
      {% if etc_exports is defined %}
      {{ etc_exports }}
      {% endif %}
    create: true
    state: present
  register: etc_exports_edit

- name: Start NFS export service
  tags: server
  service:
    name: nfs-kernel-server
    state: started
    enabled: true

- name: Restart NFS server
  tags: server
  service:
    name: nfs-kernel-server
    state: restarted
  when: etc_exports_edit.changed

- name: Export NFS
  command: |
    exportfs -a
  changed_when: false
  ignore_errors: true
  
- name: Edit fstab on NFS client
  ansible.builtin.blockinfile:
    path: /etc/fstab
    block: |
      {% if etc_fstab_nfs is defined %}
      {{ etc_fstab_nfs }}
      {% endif %}
    create: true
    state: present
  register: fstab_edit

- name: Config idmap
  ansible.builtin.lineinfile:
    path: /etc/idmapd.conf
    regexp: 'Domain ='
    line: "Domain = {{ host_domain }}"
    state: present
  when: host_domain is defined

- name: Config autoFS - edit /etc/auto.mount
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    regexp: '^/-\s+/etc/auto.mount'
    line: "/-    /etc/auto.mount"
    state: present
  when: autofs_mounts is defined

- name: Config autoFS - mountpoints
  ansible.builtin.blockinfile:
    dest: /etc/auto.mount
    marker: "# {mark} ANSIBLE MANAGED - {{ item.host }}:{{ item.origin }} "
    block: |
      {{ item.mountpoint }}   {{item.options}}  {{ item.host }}:{{ item.origin }}
    create: true
    mode: 0644
    owner: root
    group: root
    state: present
  loop: "{{ autofs_mounts }}"
  when: autofs_mounts is defined
  notify:
    - restart autofs

- name: Reload client mountpoints
  command: |
    mount -a
  when: fstab_edit.changed
