---
# tasks file for install_docker
- name: Remove legacy versions
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Install dependencies
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
    state: latest

- name: add gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install Docker CE
  package:
    name: docker-ce
    state: latest
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool | default('True')
